# Generated by Django 2.2.12 on 2022-06-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='studentmodel',
        ),
    ]
