# Generated by Django 2.2.12 on 2022-06-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20220604_0355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentmodel',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
    ]
