# Generated by Django 2.2.12 on 2022-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20220604_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_request', models.CharField(max_length=50)),
            ],
        ),
    ]
