# Generated by Django 2.2.12 on 2022-06-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_requestbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='issueBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('book', models.CharField(max_length=50)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
