# Generated by Django 2.2.12 on 2022-06-06 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0009_auto_20220606_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('inprogress', 'Inprogress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.Book')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='issue_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.request_book')),
                ('librarian_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
